Add config for jenkins container
cn-terraform/terraform-aws-jenkins pull request #49
Opened 2023-02-15 16:59 UTC by ktibi

2023-02-16 10:11 UTC, jnonino requested changes

2023-02-16 10:11 UTC, jnonino commented on main.tf
> +  container_cpu    = var.container_cpu # 2 vCPU - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html#fargate-task-defs
```suggestion
  container_cpu    = var.container_cpu
```

2023-02-16 10:11 UTC, jnonino commented on main.tf
> +  container_memory = var.container_memory # 4 GB  - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html#fargate-task-defs
```suggestion
  container_memory = var.container_memory
```

2023-02-16 10:11 UTC, jnonino commented on variables.tf
> +variable "container_memory" {
```suggestion
# https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html#fargate-task-defs
variable "container_memory" {
```

2023-02-16 10:11 UTC, jnonino commented on variables.tf
> +variable "container_cpu" {
```suggestion
# https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html#fargate-task-defs
variable "container_cpu" {
```

2023-02-16 10:11 UTC, jnonino commented on variables.tf
> +  # https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html#fargate-task-defs
```suggestion
```

2023-02-16 15:42 UTC, ktibi commented
Hi Julian,

I change the task definition for EFS.

If we keep root_directory with your config, Fargate fail because he can found the directory in the EFS.

I don't know if we can create directly the directory in the EFS with terraform. So by default I use / .

2023-02-17 11:34 UTC, jnonino commented
> Hi @jnonino Julian,
> 
> I change the task definition for EFS.
> 
> If we keep root_directory with your config, Fargate fail because it can't found the directory in the EFS.
> 
> I don't know if we can create directly the directory in the EFS with terraform. So by default I use / .

Hi @ktibi, from what I remember the Jenkins image creates that directory when started running but that might be changed! I don't feel too confortable with using `/` if you can find an alternative that'd be great!!!

[Working with Amazon EFS access points](https://docs.aws.amazon.com/efs/latest/ug/efs-access-points.html)

> Creating the root directory for an access point
If a root directory path for an access point doesn't exist on the file system, Amazon EFS automatically creates that root directory with the ownership and permissions specified.

[Terraform efs_access_point](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_access_point)

2023-02-17 11:34 UTC, jnonino commented
> Hi @jnonino Julian,
> 
> I change the task definition for EFS.
> 
> If we keep root_directory with your config, Fargate fail because it can't found the directory in the EFS.
> 
> I don't know if we can create directly the directory in the EFS with terraform. So by default I use / .

Hi @ktibi, from what I remember the Jenkins image creates that directory when started running but that might be changed! I don't feel too confortable with using `/` if you can find an alternative that'd be great!!!

[Working with Amazon EFS access points](https://docs.aws.amazon.com/efs/latest/ug/efs-access-points.html)

> Creating the root directory for an access point
If a root directory path for an access point doesn't exist on the file system, Amazon EFS automatically creates that root directory with the ownership and permissions specified.

[](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_access_point)

2023-04-19 07:55 UTC, jnonino approved these changes

2023-04-19 07:56 UTC, merged